package net.sistemasc.dbisam_error_codes;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.*;
import android.database.sqlite.SQLiteDatabase.CursorFactory;

public class MyDbAdapter {
  // database and tables names
  private static final String DATABASE_NAME    = "dbisam4_err_db";
  private static final String TABLE_NAME       = "dbisam4_err";
  private static final int    DATABASE_VERSION = 4; // ********* USED TO FORCE DB UPDATE ******* \\

  // field names
  public static final String  KEY_ID           = "_id";
  public static final String  ERR_CONST        = "ErrConst";
  public static final String  ERR_MSG          = "ErrMsg";
  public static final String  ERR_DESC         = "ErrDesc";

  // work elements
  private final Context       context;
  private SQLiteDatabase      db;
  private MyOpenHelper        openHelper;

  private class MyOpenHelper extends SQLiteOpenHelper {

//    private Context context;
    private static final String DROP_TABLE   = "DROP TABLE IF EXISTS "
                                                 + TABLE_NAME + ";";
    private static final String CREATE_TABLE = "CREATE TABLE " + TABLE_NAME
                                                 + " (" + KEY_ID
                                                 + " INTEGER PRIMARY KEY, "
                                                 + ERR_CONST + " TEXT, "
                                                 + ERR_MSG + " TEXT, "
                                                 + ERR_DESC + " TEXT);";

    public MyOpenHelper(Context _context, String _name, CursorFactory _factory,
        int _version) {
      super(_context, _name, _factory, _version);
//      context = _context;
    }

    @Override
    public void onCreate(SQLiteDatabase _db) {
      _db.execSQL(DROP_TABLE);
      _db.execSQL(CREATE_TABLE);
//      Log.i(this.context.getString(R.string.app_name),"begin table population");
      
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8705,\"DBISAM_BOF\",\"Beginning of table '<TableName>' unexpectedly encountered.\",\"This error should not normally occur since encountering the beginning of a table is a normal occurrence. The only time this error is triggered is when the beginning of the table is encountered unexpectedly. If this error does occur the most likely reason is corruption in the table, and you should repair the table. Please see the Verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8706,\"DBISAM_EOF\",\"End of table '<TableName>' unexpectedly encountered.\",\"This error should not normally occur since encountering the end of the table is a normal occurrence. The only time this error is triggered is when the end of the table is encountered unexpectedly. This error should never occur,however if it does the most likely reason is corruption in the table. You should repair the table if this error occurs. Please see the Verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8708,\"DBISAM_KEYORRECDELETED\",\"Record has been changed or deleted by another user,session, or table cursor in the table '<TableName>'.\",\"This error occurs when an attempt is made to edit or delete a record and the record has already been changed or deleted by another user, session, or table cursor since DBISAM last cached the record. Please see the Updating Tables and Query Result Sets and Change Detection topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8709,\"DBISAM_NOCURRREC\",\"No current record in the table '<TableName>'.\",\"This error occurs when DBISAM internally attempts to retrieve the current record and the current record is not present, most likely due to the table being empty because of a range or filter condition. Please see the Setting Filters on Tables and Query Result Sets, Setting Ranges on Tables,and Searching and Sorting Tables and Query Result Sets topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8710,\"DBISAM_RECNOTFOUND\",\"Record not found in the table '<TableName>'.\",\"This error occurs when a call to the TDBISAMTableGotoCurrent method fails to find the corresponding record in the destination table parameter.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8711,\"DBISAM_ENDOFBLOB\",\"End of BLOB field in the table '<TableName>' reachedprematurely.\",\"This error occurs when DBISAM attempts to read from a BLOB field that is expected to be x number of bytes in length but encounters the end of the BLOB before reaching the desired number of bytes. This error should never occur,however if it does the most likely reason is corruption in the table. You should repair the table if this error occurs. Please see the Verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8961,\"DBISAM_HEADERCORRUPT\",\"Header information corrupt in table <TableName>.\",\"This error occurs when DBISAM opens a table and detects that the actual data in the table does not match the header information, which is always an indication of corruption in the table. Please see the Verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8962,\"DBISAM_FILECORRUPT\",\"Data record buffers corrupt in the table '<TableName>'.\",\"This error occurs when DBISAM attempts to read, write, or manipulate an internal record buffer and cannot do so due to table corruption. You should repair the table if this error occurs. Please see the Verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8963,\"DBISAM_MEMOCORRUPT\",\"BLOB block buffers corrupt in the table '<TableName>'.\",\"This error occurs when DBISAM attempts to read, write, or manipulate an internal BLOB block buffer and cannot do so due to table corruption. You should repair the table if this error occurs. Please see the Verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (8965,\"DBISAM_INDEXCORRUPT\",\"Index page buffers corrupt in the table '<TableName>'.\",\"This error occurs when DBISAM attempts to read, write, or manipulate an internal index page buffer and cannot do so due to table corruption. You should repair the table if this error occurs. Please see the Verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9217,\"DBISAM_READERR\",\"Error reading from the table or backup file '<Name>'.\",\"This error occurs when DBISAM attempts to read from the table or backup file and cannot read the desired number of bytes. This error should never occur, however if it does the most likely reason is corruption in the table or backup file.You should repair the table if this error occurs with a table,but there is currently no way to recover data from a corrupted backup file. Please see the Verifying and Repairing Tables topic for more information on repairing tables.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9218,\"DBISAM_WRITEERR\",\"Error writing to the table or backup file '<Name>'.\",\"This error occurs when DBISAM attempts to write to a table or backup file and cannot write the desired number of bytes. This error should never occur, however if it does the most likely reason is corruption in the table or backup file,or a lack of available disk space. You should repair the table if this error occurs, or if the error occurs for a backup file,check the available disk space and restart the backup process. Please see the Verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9477,\"DBISAM_RECTOOBIG\",\"Maximum record size exceeded in the table '<TableName>'.\",\"This error occurs when an attempt is made to create a new table or alter an existing table's structure and doing so would exceed the maximum allowable record size. Please see Appendix C - System Capacities for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9479,\"DBISAM_TABLEFULL\",\"The table '<TableName>' is full and cannot contain anymore data.\",\"This error occurs when an attempt is made to add data to a table and doing so would cause any one of the physical files that make up a logical table to be larger than the allowable maximum file size, or it would cause the table to exceed the maximum number of allowable records. Please see appendix C - System Capacities and the Enabling Large File support for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9480,\"DBISAM_DATABASEFULL\",\"The database '<DatabaseName>' is full and cannot contain any more tables.\",\"This error occurs when an attempt is made to create a new table and doing so would cause the number of tables to exceed the maximum number of tables allowed for a given database. Please see Appendix C - System Capacities and the Creating and Altering Tables for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9482,\"DBISAM_INTERNALLIMIT\",\"Too many filters defined for the table '<TableName>'.\",\"This error occurs when DBISAM internally attempts to define more filters than allowed. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9487,\"DBISAM_INDEXLIMIT\",\"Maximum or minimum limits on the index page size, the number of indexes, or the number of fields in an index exceeded in the table '<TableName>'.\",\"This error occurs when an attempt is made to add a new primary or secondary index, create a new table, or alter an existing table's structure and doing so would exceed the maximum or minimum index page size, the maximum number of indexes, or the maximum number of fields per index that can be present in a table. Please see Appendix C- System Capacities for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9492,\"DBISAM_FLDLIMIT\",\"Maximum or minimum limits on number of fields exceeded in the table '<TableName>'.\",\"This error occurs when an attempt is made to create a new table or alter an existing table's structure and doing so would exceed the maximum or minimum number of field that can be present in a table. Please see Appendix C -System Capacities for more information. \");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9494,\"DBISAM_OPENBLOBLIMIT\",\"Too many BLOBs opened in the table '<TableName>'.\",\"This error occurs when DBISAM attempts to open more BLOBs than what is allowed. Please see Appendix C -System Capacities for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9498,\"DBISAM_BLOBLIMIT\",\"Too many BLOB fields or invalid BLOB block size specified for the table '<TableName>'.\",\"This error occurs when DBISAM internally attempts to open more blobs than allowed or attempts to create a table or alter an existing table's structure with an invalid BLOB block size. Please see Appendix C - System Capacities for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9729,\"DBISAM_KEYVIOL\",\"Duplicate key found in the index '<IndexName>' of the table '<TableName>'.\",\"This is a non-fatal error that occurs when an attempt is made to add a record to a table and the record would cause a duplicate key to be added for the primary index or for a secondary index that it is defined as being unique. Primary indexes implicitly enforce uniqueness and therefore cannot permit duplicates to be added, while secondary indexes must be explicitly defined as unique. Please see the updating Tables and Query Result Sets topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9730,\"DBISAM_MINVALERR\",\"The value for the field '<FieldName>' in the table'<TableName>' is below the minimum allowable value.\",\"This is a non fatal error that occurs when an attempt is made to add a record to a table or update a record in a table, and a field in the record would violate a minimum value constraint for that field. Constraints ensure that data is either present or within an approved range of values for any given field. Please see the Updating Tables and Query result Sets and Creating and Altering Tables topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9731,\"DBISAM_MAXVALERR\",\"The value for the field '<FieldName>' in the table'<TableName>' is above the maximum allowable value.\",\"This is a non fatal error that occurs when an attempt is made to add a record to a table or update a record in a table, and a field in the record would violate a maximum value constraint for that field. Constraints ensure that data is either present or within an approved range of values for any given field. Please see the Updating Tables and Query result Sets and Creating and Altering Tables topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9732,\"DBISAM_REQDERR\",\"A value must be provided for the field '<FieldName>' in thetable '<TableName>'.\",\"This is a non fatal error that occurs when an attempt is made to add a record to a table or update a record in a table, and a field in the record would violate a required constraint for that field. Constraints ensure that data is either present or within an approved range of values for any given field. Please see the Updating Tables and Query result Sets and Creating and Altering Tables topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9985,\"DBISAM_OUTOFRANGE\",\"Invalid field number or name '<FieldName>' specified for the table '<TableName>'.\",\"This error occurs when a field number is referenced in an operation and that field number does not exist.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9993,\"DBISAM_PRIMARYKEYREDEFINE\",\"A primary index is already defined for the table '<TableName>' and cannot be added again.\",\"This error occurs when an attempt is made to add a primary index to a table when one already exists. You must first remove the existing primary index before you can add anew one. Please see the Adding and Deleting Indexes from a Table and Creating and Altering Tables topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (9998,\"DBISAM_INVALIDBLOBOFFSET\",\"Invalid BLOB offset into the table '<TableName>' specified.\",\"This error occurs when DBISAM attempts to access a BLOB field in a table and the offset at which it is trying to access the data is invalid. This error should never occur, however if it does the most likely reason is corruption in the table. You should repair the table if this error occurs. Please see the verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10000,\"DBISAM_INVALIDFLDTYPE\",\"Invalid field definition specified for the field '<FieldName>'in the table '<TableName>'.\",\"This error occurs when an attempt is made to create a new table or alter an existing table's structure, and a field definition specified is invalid due to an incorrect field number, data type, or length. Please see the Creating and altering Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10006,\"DBISAM_INVALIDVCHKSTRUCT\",\"Invalid default expression or min/max constraint specified for the field '<FieldName>' in the table '<TableName>'.\",\"This error occurs when a default value /maximum constraint expression for the indicated field is invalid. You need to verify that the expression provided is appropriate for the data type of the indicated field. If the expression contains constants, you need to verify that the expression is properly formatted, especially with date, time, or number expressions. Please see the creating and Altering Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10010,\"DBISAM_INDEXNAMEREQUIRED\",\"The secondary index name is missing or not specified for the table '<TableName>'.\",\"This error occurs when an attempt is made to add a new secondary index and the secondary index name is missing or not specified. All secondary indexes require a unique name (case-insensitive) that is used to identify the index.Please see the Adding and Deleting Indexes from a Table and Creating and Altering Tables topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10015,\"DBISAM_INVALIDPASSWORD\",\"Password provided for the table '<TableName>' is invalid.\",\"This error occurs when an attempt is made to create a table or alter an existing table's structure with a password that . Please see the Creating and Altering Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10022,\"DBISAM_INVALIDINDEXNAME\",\"Invalid secondary index name '<IndexName>' specified for the table '<TableName>'.\",\"This error occurs when an attempt is made to set the active index to a secondary index that does not exist, delete a secondary index that does not exist, create a table or alter an existing table's structure with an index name that is invalid, or add a secondary index with an invalid index name. Please see the Searching and Sorting Tables and query Result Sets, Adding and Deleting Indexes from a Table, and Creating and Altering Tables topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10023,\"DBISAM_INVALIDIDXDESC\",\"Invalid field number '<FieldName>' specified in the index '<IndexName>' for the table '<TableName>'.\",\"This error occurs when an index definition contains an invalid field number. This error should never occur, however if it does the most likely reason is corruption in the table.You should repair the table if this error occurs. Please seethe Verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10026,\"DBISAM_INVALIDKEY\",\"Invalid key size specified in the index '<IndexName>' for the table '<TableName>'.\",\"This error occurs when an attempt is made to add a new primary or secondary index, create a new table, or alter an existing table's structure, and doing so would exceed the maximum length of an index key that can be present in a table. Please see Appendix C - System Capacities for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10027,\"DBISAM_INDEXEXISTS\",\"The secondary index '<IndexName>' already exists for the table '<TableName>'.\",\"This error occurs when an attempt is made to add a new secondary index and the secondary index name already exists in the table. All secondary indexes require a unique name (case-insensitive) that is used to identify the index.Please see the Adding and Deleting Indexes from a Table and Creating and Altering Tables topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10029,\"DBISAM_INVALIDBLOBLEN\",\"Invalid BLOB length in the table '<TableName>'.\",\"This error occurs when DBISAM attempts to access a BLOB field in the table and the length of the BLOB it is trying to access is invalid. This error should never occur, however if it does the most likely reason is corruption in the table. You should repair the table if this error occurs. Please see the verifying and Repairing Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10030,\"DBISAM_INVALIDBLOBHANDLE\",\"Invalid BLOB handle for the table '<TableName>' specified.\",\"This error occurs when DBISAM internally attempts to access a BLOB field with an invalid handle to the BLOB. This error should never occur, however if it does the most likely reason is corruption in the table. You should repair the table if this error occurs. Please see the Verifying and Repairing tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10031,\"DBISAM_TABLEOPEN\",\"The table '<TableName>' is already in use.\",\"This error occurs when an attempt is made to perform an operation on a table that requires the table to be closed in order to complete the operation. The operations that require the table to be closed are as follows:• Verifying and Repairing Tables• Creating and Altering Tables• Optimizing Tables• Upgrading Tables• Deleting Tables• Renaming Tables \");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10038,\"DBISAM_INVALIDFIELDNAME\",\"Invalid or duplicate field name '<FieldName>' specified for the table '<TableName>'.\",\"This error occurs when an attempt is made to create a table or alter an existing table's structure with a field name that is invalid. Please see the Creating and Altering Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10050,\"DBISAM_NOSUCHFILTER\",\"Invalid filter handle specified for the table '<TableName>'.\",\"This error occurs when an attempt is made by DBISAM to refer to a filter expression or callback filter that does not exist. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10051,\"DBISAM_INVALIDFILTER\",\"Filter error for the table '<TableName>' - <Message>.\",\"This error occurs when an invalid filter statement is passed to DBISAM. The most common cause of this error is improperly formatted date, time, or number constants or some other type of syntax error. Please see the Setting filters on Tables and Query Result Sets topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10221,\"DBISAM_LOCKREADLOCK\",\"Cannot read lock the lock file for the database'<DatabaseName>'.\",\"This error occurs when DBISAM internally attempts to place a read lock on the lock file (dbisam.lck) for a  and it fails. Under normal circumstances this error should never occur so if it does you should contact Elevate software immediately for a resolution to the problem.Please see the Locking and Concurrency topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10222,\"DBISAM_LOCKREADUNLOCK\",\"Cannot read unlock the lock file for the database'<DatabaseName>'.\",\"This error occurs when DBISAM internally attempts to remove a read lock on the lock file (dbisam.lck) for a given database and it fails. This error should never occur so if it does you should contact Elevate Software immediately for are solution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10223,\"DBISAM_LOCKWRITELOCK\",\"Cannot write lock the lock file for the database'<DatabaseName>'.\",\"This error occurs when DBISAM internally attempts to place a write lock on the lock file (dbisam.lck) for a given database and it fails. Under normal circumstances this error should never occur so if it does you should contact Elevate software immediately for a resolution to the problem.Please see the Locking and Concurrency topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10224,\"DBISAM_LOCKWRITEUNLOCK\",\"Cannot write unlock the lock file for the database'<DatabaseName>'.\",\"This error occurs when DBISAM internally attempts to remove a write lock on the lock file (dbisam.lck) for a  and it fails. Under normal circumstances this error should never occur so if it does you should contact Elevate software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10225,\"DBISAM_READLOCK\",\"Cannot read lock the table '<TableName>'.\",\"This error occurs when an attempt is made to place a read lock on a table and it fails. Usually this indicates a hardware failure or a failure due to an excessively large amount of write activity on a given table that is preventing the read lock from being acquired. Please see the Locking and concurrency topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10226,\"DBISAM_READUNLOCK\",\"Cannot read unlock the table '<TableName>'.\",\"This error occurs when an attempt is made to remove a read lock on a table and it fails. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10227,\"DBISAM_WRITELOCK\",\"Cannot write lock the table '<TableName>'.\",\"This error occurs when an attempt is made to place a write lock on a table and it fails. Usually this indicates a hardware failure or a failure due to an excessively large amount of read or write activity on a given table that is preventing the write lock from being acquired. Please see the Locking and concurrency topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10228,\"DBISAM_WRITEUNLOCK\",\"Cannot write unlock the table '<TableName>'.\",\"This error occurs when an attempt is made to remove a write lock on a table and it fails. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10229,\"DBISAM_TRANSLOCK\",\"Transaction cannot lock the database '<DatabaseName>'.\",\"This error occurs when an attempt is made to start a transaction and the transaction cannot place a special transaction lock on the database. Usually this indicates a hardware failure or a failure due to an excessively large amount of transaction or write activity on the database that is preventing the transaction lock from being acquired.Please see the Locking and Concurrency topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10230,\"DBISAM_TRANSUNLOCK\",\"Transaction cannot unlock the database '<DatabaseName>'.\",\"This error occurs when a transaction commits or rolls back and the transaction cannot remove the special transaction lock on the database. This error should never occur so if it does you should contact Elevate Software immediately for are solution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10241,\"DBISAM_LOCKED\",\"Cannot lock the table '<TableName>'.\",\"This error occurs when an attempt is made to lock a table that is already locked by another application or the same application. Since locking a table is the equivalent of locking all of the records in the table (including new records), this error will also occur if an attempt is made to lock a table and there are individual record(s) already locked in the table. Please see the Locking and Concurrency topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10242,\"DBISAM_UNLOCKFAILED\",\"Cannot unlock the table or record in the table'<TableName>'.\",\"This error occurs when DBISAM cannot unlock a record in a table or the entire table itself. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10253,\"DBISAM_NEEDEXCLACCESS\",\"The table '<TableName>' must be opened exclusively.\",\"This error occurs when an attempt is made to perform an operation on a table that requires the table to be opened exclusively in order to complete the operation. The operations that require exclusive use of the table are as follows: • Creating and Altering Tables• Verifying and Repairing Tables• Adding and Deleting Indexes from a Table• Optimizing Tables• Upgrading Tables• Emptying Tables\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10258,\"DBISAM_RECLOCKFAILED\",\"Cannot lock record in the table '<TableName>'.\",\"This error occurs when an attempt is made to lock a record in a table that is already locked by another application or the same application. Since locking a table is the equivalent of locking all of the records in the table (including new records), this error will also occur if an attempt is made to lock a record and there the table is already locked. Please see the Locking and Concurrency topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10498,\"DBISAM_NOTSUFFTABLERIGHTS\",\"Insufficient rights to the table '<TableName>', a password is required.\",\"This error occurs when an attempt is made to perform an operation on an encrypted table and a valid password has not been provided for the current session. Please see the starting Sessions and Opening Tables topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10753,\"DBISAM_NOTABLOB\",\"Invalid BLOB field '<FieldName>' specified for the table'<TableName>'.\",\"This error occurs when an attempt is made by DBISAM internally to perform a BLOB operation on a field that is not a BLOB field. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (10758,\"DBISAM_NOTINITIALIZED\",\"The database engine is not initialized\",\"This error occurs when an attempt is made to use the DBISAM Database System without first initializing the database engine. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11010,\"DBISAM_OSENOENT\",\"Table or backup file '<Name>' does not exist.\",\"This error occurs when an attempt is made to open a table or backup file that does not exist. Please see the Opening tables and Backing Up and Restoring Databases topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11012,\"DBISAM_OSEMFILE\",\"Too many operating system files open while attempting to open the table or backup file '<Name>'.\",\"This error occurs when an attempt is made to open up a table or backup file and the operating system rejects the open because it has run out of available file handles. With modern 32-bit operating systems this error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11013,\"DBISAM_OSEACCES\",\"Access denied to table or backup file '<Name>'.\",\"This error usually occurs when an attempt is made to open up a table or backup file and the operating system does not allow access to the table or backup file due to the fact that it has already been opened up exclusively by another application or the same application or a user rights issue. A table can be opened exclusively only once. It can also occur when an attempt is made to open up a table for read/write access that is in a read-only directory or on a read-only drive and not marked as read-only as an attribute. Please see the Opening Tables topic for more information. It is also possible that a table's backup files cannot be overwritten during the processing of altering the structure of a table,adding indexes to a table or deleting indexes from a table,or optimizing a table. Please see the Creating and Altering tables, Adding and Deleting Indexes from a Table, and Optimizing Tables topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11014,\"DBISAM_OSEBADF\",\"Invalid operating system file handle for the table or backup file '<Name>'.\",\"This error occurs when DBISAM internally attempts to perform an operation on a table or backup file using an invalid file handle. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11016,\"DBISAM_OSENOMEM\",\"There is insufficient operating system memory available for the current operation.\",\"This error is reported by the memory manager in Delphi,Kylix, or C++Builder when there is insufficient memory available for current operation. If you receive this error you should contact Elevate Software in order to find out how to reduce the amount of memory being consumed and to find alternate solutions to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11023,\"DBISAM_OSENODEV\",\"Access denied to logical operating system device for the table or backup file '<Name>'.\",\"This error occurs when the operating system reports that the logical device for the table or backup file is invalid or inaccessible. This problem can occur with removable disks in floppy drives or CD-ROM drives.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11025,\"DBISAM_OSENOTSAM\",\"The table or backup file '<Name>' has been moved.\",\"This error occurs when the operating system detects that a table or backup file has been moved from one device to another after being opened. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11047,\"DBISAM_OSUNKNOWN\",\"An unknown operating system error <OSErrorCode>occurred with the table or backup file '<Name>'.\",\"This error occurs when DBISAM detects a general operating system error, indicated by the error code in the error message, but cannot translate it into a more specific error message. DBISAM identifies and translates certain operating system errors such as sharing violations, file and directory not found errors, etc. into specific error messages. If you receive this error you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11276,\"DBISAM_REMOTECOMMLOST\",\"The connection to the database server at '<RemoteName>'has been lost.\",\"This error occurs when an application attempts an operation on a database server, the operation fails, and DBISAM is unable to automatically re-connect to the database server. This is most often caused by a physical interruption in the connection between the client and server processes. Please see the Starting Sessions topic for more information. \");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11277,\"DBISAM_REMOTEENCRYPTREQ\",\"The database server at '<RemoteName>' requires an encrypted connection.\",\"This error occurs when an application attempts a regular connection to a database server and the database server requires encrypted connections only. This error can also occur if an administrator is attempting to connect to the administrative port on the database server and the connection is unencrypted. Administrative connections always require encryption. Please see the Starting Sessions and Server Administration topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11279,\"DBISAM_REMOTEUNKNOWN\",\"An unknown error ('<Message>') occurred with the connection to the database server at '<RemoteName>',please check the server log.\",\"This error occurs when an unknown error has occurred during an operation on the database server. You should check the server log as soon as possible using an administrative connection in order to find out the nature of the error. Please see the Server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11280,\"DBISAM_REMOTECONNECT\",\"A connection to the database server at '<RemoteName>'cannot be established.\",\"This error occurs when an application attempts to connect to a database server via a TDBISAMSession component and the connection fails. This is most often caused by the lack of a server process listening on the specified port at the specified IP address. Please see the Starting Sessions topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11281,\"DBISAM_REMOTENOLOGIN\",\"A connection to the database server at '<RemoteName>'cannot be established, the server is not accepting new logins.\",\"This error occurs when an application attempts to connect to a database server and the connection fails because the server administrator has configured the server to refuse any new logins. Please see the Starting Sessions and Server administration topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11282,\"DBISAM_REMOTEMAXCONNECT\",\"A connection to the database server at '<RemoteName>'cannot be established, the maximum number of server or user connections has been reached.\",\"This error occurs when an application attempts to connect to a database server and the connection fails because the maximum number of connections configured for the server would be exceeded by the new connection. This error can also occur when a user connects and logs in to the database server and the maximum number of connections configured for that user would be exceeded by the new connection. Please see the Starting Sessions and Server Administration topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11283,\"DBISAM_REMOTEADDRESSBLOCK\",\"A connection to the database server at '<RemoteName>'cannot be established, the client address is blocked\",\"This error occurs when an application attempts to connect to a database server and the connection fails because the IP address of the machine the application is running on has been blocked in the server configuration. Please see the starting Sessions and Server Administration topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11285,\"DBISAM_REMOTECALLBACKERR\",\"A server callback error occurred for the database server at'<RemoteName>'.\",\"This error occurs when an internal callback used by DBISAM when connected to a database server fails for some reason. This error should never occur so if it does you should contact Elevate Software immediately for a resolution to the problem.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11286,\"DBISAM_REMOTEVERSION\",\"A call to the database server at '<RemoteName>' failed, the client engine version does not match the server.\",\"This error occurs when an application attempts to execute functionality that results in a call to a database server, and the call fails because the DBISAM version of the application does not match the required version of the database server for that particular call. Only in certain cases where database server calls have been altered due to an enhancement or bug fix will this error be seen, and those cases will be documented in an incident report. Please see the Starting sessions topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11287,\"DBISAM_REMOTEINVLOGIN\",\"A connection to the database server at '<RemoteName>'cannot be established, the login information provided is invalid.\",\"This error occurs when an application attempts to connect to a database server and the connection fails because the login information (user name and/or password) specified is invalid. Please see the Starting Sessions topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11288,\"DBISAM_REMOTENOTAUTH\",\"The user '<UserName>' is not authorized to perform this operation with the database '<DatabaseName>' on the database server at '<RemoteName>'.\",\"This error occurs when an application attempts to perform a function on a database server and it fails because the user has not been granted rights to perform such a function on the current database. Please see the Server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11289,\"DBISAM_REMOTENOTADMIN\",\"The user '<UserName>' is not authorized to perform administration functions on the database server at'<RemoteName>'.\",\"This error occurs when an application attempts to perform an administrative function on a database server and it fails because the user is not designated as an administrator fort hat database server. Please see the Server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11290,\"DBISAM_REMOTEINVUSER\",\"The user name is either invalid or blank.\",\"This error occurs when an attempt is made to add a new user to a database server and the user name is either missing or invalid. Only administrators can add new users to a database server. Please see the Server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11291,\"DBISAM_REMOTENOUSER\",\"The user '<UserName>' does not exist on the database server at '<RemoteName>'.\",\"This error occurs when an application attempts to edit or remove a user on a database server that does not exist.Only administrators can edit or remove users from a database server. Please see the Server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11292,\"DBISAM_REMOTEDUPUSER\",\"The user '<UserName>' already exists on the databaseserver at '<RemoteName>'.\",\"This error occurs when an attempt is made to add a new user to a database server and the user name (case insensitive)already exists on that database server. Only administrators can add users to a database server. Please see the Server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11293,\"DBISAM_REMOTEINVDB\",\"The database name or directory is either invalid or blank.\",\"This error occurs when an attempt is made to add a new database to a database server and the database name is either missing or invalid or the directory specified cannot be created from the server. Only administrators can add databases to a database server. Please see the Server administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11294,\"DBISAM_REMOTENODB\",\"The database '<DatabaseName>' does not exist on the database server at '<RemoteName>'.\",\"This error occurs when an application attempts to edit or remove a database that does not exists from a database server. Only administrators can edit or remove databases from a database server. Please see the Server administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11295,\"DBISAM_REMOTEDUPDB\",\"The database '<DatabaseName>' already exists on the database server at '<RemoteName>'.\",\"This error occurs when an attempt is made to add a new database to a database server and the database name(case-insensitive) already exists on that database server.Only administrators can add databases to a database server. Please see the Server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11296,\"DBISAM_REMOTEINVDBUSER\",\"The database user name is either invalid or blank.\",\"This error occurs when an attempt is made to add a new user to a database on a database server and the user name is either missing or invalid. Only administrators can add users to a given database on a database server. Please seethe Server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11297,\"DBISAM_REMOTENODBUSER\",\"The database user '<UserName>' does not exist for the database '<DatabaseName>' on the database server at'<RemoteName>'.\",\"This error occurs when an application attempts to edit or remove a user that does not exist from a database on a database server. Only administrators can edit or remove users from a given database on a database server. Please see the Server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11298,\"DBISAM_REMOTEDUPDBUSER\",\"The database user '<UserName>' already exists for the database '<DatabaseName>' on the database server at'<RemoteName>'.\",\"This error occurs when an attempt is made to add a new user to a database on a database server and the user name(case-insensitive) already exists for the specified database on that database server. Only administrators can add users to a given database on a database server. Please see the server Administration topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11299,\"DBISAM_REMOTEINVPROC\",\"The procedure name is either invalid or blank.\",\"This error occurs when an attempt is made to add a new server-side procedure to a database server and the procedure name is either missing or invalid. Only administrators can add server-side procedures to a database server. Please see the Server Administration and Customizing the Engine topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11300,\"DBISAM_REMOTENOPROC\",\"The procedure '<ProcedureName>' does not exist on the database server at '<RemoteName>'.\",\"This error occurs when an application attempts to edit or remove a server-side procedure that does not exist from a database server. Only administrators can edit or remove server-side procedures from a database server. Please seethe Server Administration and Customizing the Engine topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11301,\"DBISAM_REMOTEDUPPROC\",\"The procedure '<ProcedureName>' already exists on the database server at '<RemoteName>'.\",\"This error occurs when an attempt is made to add a new server-side procedure to a database server and the procedure name (case-insensitive) already exists on that database server. Only administrators can add server-side procedures to a database server. Please see the Server administration and Customizing the Engine topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11302,\"DBISAM_REMOTEINVPROCUSER\",\"The procedure user name is either invalid or blank.\",\"This error occurs when an attempt is made to add a new user to a server-side procedure on a database server and the user name is either missing or invalid. Only administrators can add users to a given server-side procedure on a database server. Please see the Server administration and Customizing the Engine topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11303,\"DBISAM_REMOTENOPROCUSER\",\"The procedure user '<UserName>' does not exist for the procedure '<Procedure name>' on the database server at'<Remote name>'.\",\"This error occurs when an application attempts to edit or remove a user that does not exist from a server-side procedure on a database server. Only administrators can edit or remove users from a given server-side procedure on a database server. Please see the Server Administration and Customizing the Engine topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11304,\"DBISAM_REMOTEDUPPROCUSER\",\"The procedure user '<UserName>' already exists for the procedure '<ProcedureName>' on the database server at'<RemoteName>'.\",\"This error occurs when an attempt is made to add a new user to a server-side procedure on a database server and the user name (case-insensitive) already exists for the specified procedure on that database server. Only administrators can add users to a given server-side procedure on a database server. Please see the Server administration and Customizing the Engine topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11305,\"DBISAM_REMOTEINVEVENT\",\"The event name is either invalid or blank.\",\"This error occurs when an attempt is made to add a new scheduled event to a database server and the event name  missing or invalid. Only administrators can  events to a database server. Please see the server Administration and Customizing the Engine topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11306,\"DBISAM_REMOTENOEVENT\",\"The event '<EventName>' does not exist on the database server at '<RemoteName>'.\",\"This error occurs when an application attempts to edit or remove a scheduled event that does not exist from a database server. Only administrators can edit or remove scheduled events from a database server. Please see the server Administration and Customizing the Engine topics for more information. \");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11307,\"DBISAM_REMOTEDUPEVENT\",\"The event '<EventName>' already exists on the database server at '<RemoteName>'.\",\"This error occurs when an attempt is made to add a new scheduled event to a database server and the event name(case-insensitive) already exists on that database server.Only administrators can add scheduled events to a database server. Please see the Server Administration and Customizing the Engine topics for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11308,\"DBISAM_REMOTEINVREQUEST\",\"An invalid or unknown request was made to the database server at '<RemoteName>'.\",\"This error occurs when an application makes a call to a database server that is invalid or malformed. This error should never occur under normal operation, but if it does it usually indicates an improper client engine or an attempt to break into the server.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11310,\"DBISAM_EXPORTERROR\",\"An error occurred during the export from the table'<TableName>' - <Message>.\",\"This error occurs when any error is encountered during the export of a table to a text file. The message will give the specific details of the error and why the error occurred.Please see the Importing and Exporting Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11311,\"DBISAM_IMPORTERROR\",\"An error occurred during the import into the table'<TableName>' - <Message>.\",\"This error occurs when any error is encountered during the import of a text file into a table. The message will give the specific details of the error and why the error occurred.Please see the Importing and Exporting Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11312,\"DBISAM_LOADSTREAMERROR\",\"An error occurred during the loading of a stream into the table '<TableName>' - <Message>.\",\"This error occurs when any error is encountered during the loading of a stream into a table. The message will give the specific details of the error and why the error occurred.Please see the Loading and Saving Streams topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11313,\"DBISAM_SAVESTREAMERROR\",\"An error occurred during the saving of the table'<TableName>' to a stream - <Message>.\",\"This error occurs when any error is encountered during the saving of a table or query to a stream. The message will give the specific details of the error and why the error occurred. Please see the Loading and Saving Streams topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11314,\"DBISAM_TRIGGERERROR\",\"An error occurred during a trigger on the table'<TableName>' - <Message>.\",\"This error occurs when any error is encountered during the execution of an insert, update, or delete trigger for a table.The message will give the specific details of the error and why the error occurred. Please see the Customizing the engine topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11949,\"DBISAM_SQLPARSE\",\"SQL parsing error - <Message>.\",\"This error occurs when any error is encountered during the parsing or preparation of an SQL statement. The message will give the specific details of the error and why the error occurred. Please see the TDBISAMQuery OnQueryErrorevent for more information on trapping these kind of errors. \");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (11950,\"DBISAM_SQLEXEC\",\"SQL execution error - <Message>.\",\"This error occurs when any error is encountered during the execution of an SQL statement. The message will give the specific details of the error and why the error occurred.Please see the TDBISAMQuery OnQueryError event for more information on trapping these kind of errors.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (12035,\"DBISAM_OLDVERSION\",\"The table '<TableName>' is not the correct version.\",\"This error occurs when an attempt is made to open a table that is either the incorrect version for the current version of DBISAM or is not a DBISAM table at all (but may have the same extensions as the physical files that make up a logical DBISAM table). Please see the Upgrading Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (12036,\"DBISAM_BADSIGNATURE\",\"The table or backup file '<Name>' is not valid.\",\"This error occurs when an attempt is made to open a table or backup file that was created using a different engine signature than the current engine signature in use. It is also possible that the file is not a DBISAM table at all (but may have the same extensions as the physical files that make up a logical DBISAM table).\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (12292,\"DBISAM_SEARCHCOLREQD\",\"Invalid field type specified for the index '<IndexName>' in the table '<TableName>'.\",\"This error occurs when an attempt is made to add a primary or secondary index, create a table, or alter an existing table's structure and one or more of the indexes contain BLOB fields as one of the index fields. BLOB fields cannot be directly indexed in DBISAM and must be indexed using the full text indexing instead. Please see the Full Text Indexing topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (13060,\"DBISAM_TABLEEXISTS\",\"The table '<TableName>' already exists.\",\"This error occurs when an attempt is made to create a table and the table already exists. Please see the Creating and altering Tables topic for more information.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (15001,\"DBISAM_COMPRESS\",\"Error compressing data.\",\"This error occurs when DBISAM attempts to compress a buffer and the compression fails. This error should never occur, so if you receive this error you should immediately contact Elevate Software for more information on how to resolve this issue.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (15002,\"DBISAM_UNCOMPRESS\",\"Error uncompressing data.\",\"This error occurs when DBISAM attempts to uncompress a buffer and the uncompression fails. This error should never occur, so if you receive this error you should immediately contact Elevate Software for more information on how to resolve this issue.\");");
      _db.execSQL("INSERT INTO "+TABLE_NAME+" VALUES (15878,\"DBISAM_CANNOTLOADLDDRV\",\"The locale support for the table '<TableName>' is not available or installed.\",\"This error occurs when an attempt is made to open or create a table with a locale that is not available or installed on the current machine's operating system. Certain locales are only available when specifically installed on the target machine. Linux only supports the default ANSI Standard locale in DBISAM. Please see the Creating and Altering Tables topic for more information.\");");
      
//      Log.i(this.context.getString(R.string.app_name),"end table population");
    }

    @Override
    public void onUpgrade(SQLiteDatabase _db, int _oldVersion, int _newVersion) {
//      Log.w("MyDbAdapter", "Upgrading from version "+_oldVersion+" to "+_newVersion);
      onCreate(_db);
    }

  }

  public MyDbAdapter(Context _context) {
    this.context = _context;
    openHelper = new MyOpenHelper(context, DATABASE_NAME, null,
        DATABASE_VERSION);
  }

  public void close() {
    db.close();
  }

  public void open() throws SQLiteException {
    try {
      db = openHelper.getReadableDatabase();
    } catch (SQLiteException ex) {
      ex.printStackTrace();
    }
  }

  public Cursor getAllRows() {
    return db.query(TABLE_NAME, new String[] { KEY_ID,ERR_CONST,ERR_MSG,ERR_DESC }, null, null, null, null,
        KEY_ID);
  }

}
